{% set name = "jupyter_server" %}
{% set version = "1.13.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fb5a219385338b1d13a013a68f54688b6a69ecff4e757fd230e27ecacdbf212

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-server = jupyter_server.serverapp:main

requirements:
  host:
    - jupyter-packaging >=0.9,<1
    - pip
    - python >=3.7
  run:
    - anyio >=3.1.0,<4
    - argon2-cffi
    - ipython_genutils
    - jinja2
    - jupyter_client >=6.1.1
    - jupyter_core >=4.6.0
    - nbconvert
    - nbformat
    - packaging
    - prometheus_client
    - python >=3.7
    - pyzmq >=17
    - send2trash
    - terminado >=0.8.3
    - tornado >=6.1.0
    - traitlets >=5
    - websocket-client

test:
  requires:
    - pip
  commands:
    - pip check
    - jupyter server -h
  imports:
    - jupyter_server
  downstreams:
    - jupyterlab_server
    - jupyterlab

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Jupyter Server
  description: The Jupyter Server provides the backend for Jupyter web applications such as the Jupyter notebook and JupyterLab.
  dev_url: https://github.com/jupyter/jupyter_server
  doc_url: https://jupyter-server.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - blink1073
    - minrk
    - jasongrout
    - bollwyvl
    - Zsailer
